name: lgos

networks:
  lgos-network:
    name: lgos-network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.31.0/24

services:
  postgres:
    image: postgres:18.4-alpine3.23
    container_name: lgos-postgres
    restart: "no"
    networks:
      - lgos-network
    ports:
      - 5432:5432
    volumes:
      - ./docker/volumes/lgos-db:/var/lib/postgresql
    environment:
      POSTGRES_USER: lgos
      POSTGRES_PASSWORD: lgos
      POSTGRES_DB: lgos
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lgos -d lgos"]
      interval: 5s
      timeout: 5s
      retries: 5

  lgos-demo-api:
    image: lgos-demo-api:latest
    container_name: lgos-demo-api
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: development
    networks:
      - lgos-network
    depends_on:
      postgres:
        condition: service_healthy
    pre_start:
      - command: ["uv", "run", "--module", "demo.api.setup_checkpointer"]
    ports:
      - 8000:8000
    # command: ["tail", "-f", "/dev/null"] # NOTE: For testing the container
    command: ["uv", "run", "--module", "demo.api.app"]
    restart: "no"
    environment:
      DEMO_POSTGRES_URI: postgresql://lgos:lgos@postgres:5432/lgos
      DEMO_OPENAI_BASE_URL: ${DEMO_OPENAI_BASE_URL:-https://api.openai.com/v1}
      DEMO_OPENAI_API_KEY: ${DEMO_OPENAI_API_KEY:-DUMMY}
      DEMO_OPENAI_MODEL: ${DEMO_OPENAI_MODEL:-gpt-5.4-mini}
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment
          ignore:
            - .venv/

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml

  # NOTE: Disable Title Generation: Admin Panel -> Interface -> Title Generation -> Disable
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:v0.9.6@sha256:90eae5b419e40b4c3dd684582b2c83440b36f9ae2f6532c09639b2ba4ee65158
    restart: "no"
    depends_on:
      - lgos-demo-api
    networks:
      - lgos-network
    ports:
      - 8080:8080
    volumes:
      - ./docker/volumes/open-webui:/app/backend/data
    environment:
      ENABLE_PERSISTENT_CONFIG: false
      ############# WEBUI #############
      WEBUI_NAME: LGOS-OpenwebUI
      ENABLE_OLLAMA_API: false
      ENABLE_FOLLOW_UP_GENERATION: false
      ENABLE_TAGS_GENERATION: false
      ENABLE_PIP_INSTALL_FRONTMATTER_REQUIREMENTS: false
      OFFLINE_MODE: true
      HF_HUB_OFFLINE: 1
      ############# AUTH #############
      WEBUI_ADMIN_EMAIL: lgos@example.com
      WEBUI_ADMIN_PASSWORD: lgos
      WEBUI_ADMIN_NAME: LGOS
      ############# OPENAI API #############
      ENABLE_OPENAI_API: false
      ENABLE_IMAGE_GENERATION: false
      ############# RAG #############
      RAG_EMBEDDING_ENGINE: openai
