name: Publish to PyPI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Update version in pyproject.toml
        run: sed -i "s/version = \"[^\"]*\"/version = \"${{ github.ref_name }}\"/" pyproject.toml

      - name: Build wheel
        run: uv build --wheel --out-dir dist

      - name: Publish to PyPI
        run: uv publish dist/*
